___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 1.2 MB/s eta 0:00:00m eta 0:00:010:01:01
Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

np.array(list) -> converts a python list into a numpy array

Numpy arrays support efficient numerical operations that regular python lists dont

example:
my_list = [1,2,3] ---> print(my_list*2) ---> this duplicates the list = [1,2,3,1,2,3]

But with numpy arrays:

arr = np.array([1, 2, 3])

print(arr * 2) ---> multiplies each element with 2
# [2 4 6]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]] # 3 rows and 3 columns
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [7]:
np.arange(0,10)
#arange produces range of numbers ([start],[stop],[step]) upto but not including the stop value

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2) #jump in steps of 2

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [9]:
np.zeros(3) #Why are the zeros written as 0. instead of 0?

# By default, NumPy creates a floating-point array:

array([0., 0., 0.])

In [26]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [12]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [14]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

An idenity matrix is a square matrix with 

1s on the main diagonal (top left to bottom right)

0s everywhere else 

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [16]:
np.random.rand(2) # generates 2 numbers between 0 and 1

array([0.55598759, 0.12708852])

In [13]:
np.random.rand(10) #generates 10 numbers between 0 and 1 

array([0.86790041, 0.75902867, 0.50447551, 0.74317174, 0.99810572,
       0.88603275, 0.53535538, 0.5135024 , 0.32892471, 0.6147204 ])

In [17]:
np.random.rand(5,5) # generates a 5 x 5 matrix of numbers between 0 and 1

array([[0.48464948, 0.73844949, 0.02568568, 0.25029802, 0.47530993],
       [0.34356836, 0.49776934, 0.65250089, 0.9025424 , 0.15928017],
       [0.787462  , 0.00890254, 0.21247056, 0.71918632, 0.99969552],
       [0.04071845, 0.17613293, 0.96403205, 0.19110593, 0.92206649],
       [0.7357976 , 0.32505439, 0.91880579, 0.60150284, 0.62311126]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [14]:
np.random.randn(10)

array([-0.0559495 ,  0.11687199, -1.8725597 ,  0.15684603,  0.48718442,
       -2.46697343,  1.39393331, -0.77584514, -0.23164799, -1.53378894])

In [15]:
np.random.randn(10,10)

array([[ 1.87940014, -1.71601743, -1.3184817 ,  0.94826143,  0.18654302,
        -0.79942784, -0.35786288, -0.04845641, -1.60497822, -0.08438812],
       [-0.45422474, -1.88876112,  1.69962979, -0.5529278 ,  0.17351921,
        -0.93556858,  1.09996432, -0.64457708, -1.12662976,  1.16537073],
       [-1.0044807 ,  0.55979766,  0.11058054, -0.59306554,  1.9289653 ,
         0.25384834,  1.00160232,  2.72618915, -2.03407246, -0.64448497],
       [ 0.55864433,  1.64074184,  0.11918939, -1.94356551,  0.00636486,
        -0.8010623 , -0.72616261, -1.35510108,  0.87891345,  0.53926116],
       [ 0.13799499, -0.62217813, -0.73869748,  0.17872328,  1.03126255,
        -0.01781958,  2.23285167, -0.23580242,  0.22299282, -1.09079067],
       [ 0.40175026, -0.48164115, -1.3939804 ,  1.00020124, -0.39272639,
        -0.09258102, -0.02507484,  0.6594234 ,  1.64476572,  0.08410002],
       [ 0.6381221 ,  0.07697357,  0.67470225,  0.89014604,  1.98409993,
         0.95295326, -1.13332577, -0.67870877

In [16]:
np.random.randn(5,5)

array([[-0.39473702,  1.24241873, -1.65323748,  0.37192139,  0.21065356],
       [-0.04823114, -2.11476813, -0.77157682, -0.09716211, -0.10246378],
       [ 1.26209492,  0.73861187, -0.84928854, -0.49459952,  1.0880806 ],
       [-0.02133284, -0.89476837,  0.31019423, -0.16586008,  1.04058331],
       [ 0.96732627,  0.89136497, -2.08711459, -0.8646978 , -1.99268115]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [18]:
np.random.randint(1,100) #generates a whole number between 1 and 100 but not including 100

16

In [19]:
np.random.randint(1,100,10) #generates 10 random numbers between 1 and 100

array([23, 95, 65, 91, 26, 14, 28, 52, 62, 40])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [20]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
ranarr

array([17, 10,  8,  6,  8, 24, 44, 41, 41,  6])

## Reshape
Returns an array containing the same data with a new shape.

Reshape means ---> “Take the same numbers, but arrange them differently."

but not randomly once re-arranged however many times you try running it it will be the same

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [28]:
ranarr

array([17, 10,  8,  6,  8, 24, 44, 41, 41,  6])

In [29]:
ranarr.max() #returns the largest values in the array

np.int64(44)

In [30]:
ranarr.argmax() #returns the position(index) of the largest value

np.int64(6)

In [33]:
ranarr.min() #returns the smallest values in the array

np.int64(6)

In [34]:
ranarr.argmin() #returns the position(index) of the largest value

np.int64(3)

## Shape

Shape is an attribute that arrays have (not a method):

It tells you  the size/dimensions of a Numpy array basically how many rows,columns etc.

In [65]:
# Vector
arr.shape # returns (25,) which means 1 row of data and 25 elements

(25,)

In [35]:
arr1 = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr1.shape) # 

(2, 3)


In [36]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [37]:
arr.reshape(1,25).shape

(1, 25)

In [38]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [39]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [40]:
arr.dtype

dtype('int64')

# Great Job!