___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(0,11)

In [3]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [4]:
#Get a value at an index
arr[8]

np.int64(8)

In [5]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [6]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

# NumPy Broadcasting

## What is Broadcasting?

**Broadcasting** is NumPy's way of automatically expanding a smaller array so it can perform element-wise operations with a larger array.

Think of it as:

> "If the shapes are compatible, NumPy will stretch the smaller array to match the larger one."

The important thing is that NumPy does this efficiently without actually creating huge copies of the data.

---

# Type 1: Scalar Broadcasting

A scalar (single value) is broadcast to every element.

```python
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr + 10)
```

Output:

```python
[11 12 13 14]
```

NumPy treats it as:

```python
[1, 2, 3, 4]
+
[10,10,10,10]
```

---

## Example: Assignment Broadcasting

```python
arr = np.arange(0, 11)

arr[0:5] = 100

print(arr)
```

Output:

```python
[100 100 100 100 100   5   6   7   8   9  10]
```

NumPy acts as if you wrote:

```python
arr[0:5] = [100, 100, 100, 100, 100]
```

The single value `100` is broadcast to all positions in the slice.

---

# Type 2: Same Shape Arrays

No broadcasting is needed because the shapes already match.

```python
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a + b)
```

Output:

```python
[11 22 33]
```

Shapes:

```python
(3,)
(3,)
```

---

# Type 3: Row Vector Broadcast Across Rows

```python
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([10, 20, 30])

print(A + B)
```

Shapes:

```python
A -> (2,3)
B -> (3,)
```

NumPy treats `B` like:

```python
[[10,20,30],
 [10,20,30]]
```

Result:

```python
[[11 22 33]
 [14 25 36]]
```

Visualization:

```text
A

1 2 3
4 5 6

B

10 20 30
```

Broadcasted to:

```text
10 20 30
10 20 30
```

---

# Type 4: Column Vector Broadcast Across Columns

```python
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [10],
    [20]
])

print(A + B)
```

Shapes:

```python
A -> (2,3)
B -> (2,1)
```

NumPy expands `B` to:

```python
[[10,10,10],
 [20,20,20]]
```

Result:

```python
[[11 12 13]
 [24 25 26]]
```

Visualization:

```text
A

1 2 3
4 5 6

B

10
20
```

Broadcasted to:

```text
10 10 10
20 20 20
```

---

# Type 5: Broadcasting with New Dimensions

Often done using `np.newaxis`.

```python
x = np.array([1, 2, 3])

print(x[:, np.newaxis])
```

Output:

```python
[[1]
 [2]
 [3]]
```

Shape changes:

```python
(3,) -> (3,1)
```

Now:

```python
x = np.array([1, 2, 3])

result = x[:, np.newaxis] + x

print(result)
```

Result:

```python
[[2 3 4]
 [3 4 5]
 [4 5 6]]
```

Shapes:

```python
(3,1)
(3,)
```

Broadcasting makes the operation possible.

---

# Type 6: Broadcasting in 3D Arrays

Example: RGB images.

Suppose:

```python
image.shape
```

returns:

```python
(100, 200, 3)
```

Meaning:

```text
100 rows
200 columns
3 color channels (R,G,B)
```

Now:

```python
image + np.array([10, 20, 30])
```

Shapes:

```python
(100,200,3)
(3,)
```

NumPy applies:

```python
[10,20,30]
```

to every pixel.

Useful for:

- Brightness adjustments
- Color corrections
- Image filtering

---

# Broadcasting Rules

NumPy compares shapes from **right to left**.

Two dimensions are compatible if:

1. They are equal
2. One of them is `1`

---

## Example 1

Shapes:

```python
(4,3)
(3,)
```

Comparison:

```text
3 == 3 ✓
4 vs missing → treated as 1 ✓
```

Works.

Result shape:

```python
(4,3)
```

---

## Example 2

Shapes:

```python
(2,3)
(2,1)
```

Comparison:

```text
3 vs 1 ✓
2 vs 2 ✓
```

Works.

Result shape:

```python
(2,3)
```

---

## Example 3

Shapes:

```python
(5,4,3)
(4,3)
```

Comparison:

```text
3 == 3 ✓
4 == 4 ✓
5 vs missing → treated as 1 ✓
```

Works.

Result shape:

```python
(5,4,3)
```

---

# When Broadcasting Fails

Example:

```python
A = np.zeros((2,3))
B = np.array([1,2,3,4])

A + B
```

Shapes:

```python
(2,3)
(4,)
```

Comparison:

```text
3 vs 4 ✗
```

Neither dimension is `1`.

Result:

```python
ValueError:
operands could not be broadcast together
```

---

# Real-World Applications

## 1. Add a Constant to Every Element

```python
salary + 500
```

Give everyone a bonus.

---

## 2. Data Normalization

```python
X = X - X.mean(axis=0)
```

Subtract column means from every row.

Used in Machine Learning.

---

## 3. Neural Networks

```python
outputs + bias
```

Bias vector is broadcast across all samples.

---

## 4. Image Processing

```python
image + [20,20,20]
```

Increase image brightness.

---

## 5. Pairwise Distance Calculations

```python
points[:, None, :] - points
```

Computes all point differences without loops.

Used in:

- Clustering
- KNN
- Scientific Computing
- Machine Learning

---

# Mental Model

Whenever you see:

```python
large_array OP smaller_array
```

Ask:

> Can NumPy stretch dimensions of size 1 (or missing dimensions) so the shapes match?

If yes → Broadcasting happens.

If no → NumPy raises a `ValueError`.

---

# One-Line Summary

**Broadcasting allows NumPy to automatically stretch smaller arrays (or scalars) across larger arrays so element-wise operations can be performed efficiently without writing loops.**

In [7]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [11]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [12]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [13]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [9]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [10]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [11]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

np.int64(20)

In [12]:
# Getting individual element value
arr_2d[1,0]

np.int64(20)

In [24]:
arr_2d[2][1]

np.int64(40)

In [18]:
# 2D array slicing

#Shape (2,2) from top right corner row,column
arr_2d[:2,1:] # return the rows at index 0 & 1 and their columns at index till the second last column

array([[10, 15],
       [25, 30]])

In [26]:
arr_2d[:,2]

array([15, 30, 45])

#### In NumPy, you are not selecting whole Python lists as objects. Instead, you are selecting a sub-block of values from the same array, and NumPy returns it as a new 2D array: 

#### arr_2d[row_start:row_end, col_start:col_end]

### <u> Step by Step meaning: </u>

#### <u> Row slicing ---> Selects a range of rows </u>

##### row_start:row_end eg: 0:2 meaning take rows 0 and 1

#### So : 
#### [5, 10, 15]
#### [20, 25, 30]


#### <u> Column slicing ---> Selects a range of columns </u>

##### col_start:col_end eg: 1: meaning columns 1 and 2 so from each row 

#### [5, 10, 15]  ----> [10,15]
#### [20, 25, 30] ----> [25,30]


### Final answer:

### array([
###  [10, 15],
###  [25, 30]
### ])


In [13]:
#Shape bottom row
arr_2d[2] # return the row at index 2

array([35, 40, 45])

In [14]:
#Shape bottom row
arr_2d[2,:] #return the row at index 2 and all the columns in row index 2

array([35, 40, 45])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [15]:
#Set up matrix
arr2d = np.zeros((10,10))

In [16]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
arr2d.shape[1] #remember .shape() returns the dimensions of an array

10

1. .shape is an attribute of a NumPy array that tells you its dimensions.

It returns a tuple.

Example:
arr = np.zeros((10, 10))

arr.shape

(10,10) ---> 10 rows and 10 columns


2. Understanding the tuple

The shape is just a normal Python tuple:

shape = (10, 10)

You can think of it like a list of dimensions:

First number → rows

Second number → columns


3. What is .shape[i]?

Since .shape is a tuple, you can access parts of it using indexing:

arr.shape = (10, 10)

arr.shape[0]  # 10 → rows

arr.shape[1]  # 10 → columns



arr.shape[0] is exactly like (10, 10)[0]



In [20]:
#Length of array
arr_length = arr2d.shape[1] # arr_length stores the size of the arr2d since .shape returns the dimension

In [21]:
arr_length

10

In [22]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

#loop through the array arr2d n being the size of arr2d(10) then assign all the  current index of iteration that current index in iteration

# so we're looping 10 times for each i

# We loop through the range of the array size (0 to 9).
# In each iteration, we select row i of the 2D array and assign the value i to every element in that row.

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [24]:
arr2d[[2,4,6,8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

In [25]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.]])

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to fins useful images, like this one:

<img src= 'http://memory.osu.edu/classes/python/_images/numpy_indexing.png' width=500/>

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [28]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [31]:
bool_arr = arr>4

In [32]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [33]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [34]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Great Job!
