In [1]:
import numpy as np

In [2]:
#creating a numpy array manually
np.array([1,2,3])

array([1, 2, 3])

#dimensions and shape of an array

32 -> scalar -> 0 dimensions

[1,2,3] -> 1 dimension

---->
|1234  2 dimension
|5678
|

In [4]:
#how to check dimensions
arr = np.array([1,2,3])
arr.ndim

1

# also brackets are really important with increase in brackets(inner-brackets)
# then theres increase in dimension

[] 1 dimension

[[]] 2 dimensions

[[[]]] 3 dimensions

In [11]:
a = np.array([[[]]])
a.ndim

3

In [12]:
a.shape #number of rows & number of columns 

(1, 1, 0)

In [15]:
#creating a numpy array using built in function
#range
arr1 = np.arange(1,10,2)
arr1

array([1, 3, 5, 7, 9])

In [17]:
#linspace
arr2 = np.linspace(0,1,5)
arr2

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
#logarithmic array
arr3 = np.logspace(1,3,3) #10^1 10^2 10^3  3points
arr3
#logspace(startpower,ending power,how many values on my scale)

array([  10.,  100., 1000.])

In [21]:
#create an array full of zeros np.zeros
arr4 = np.zeros(5)
arr4

array([0., 0., 0., 0., 0.])

In [23]:
#creating a matrix
arr5 = np.zeros([2,3])
arr5

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
arr5 = np.ones([2,3])
arr5

array([[1., 1., 1.],
       [1., 1., 1.]])